### ISSUE TITLE
1

### ISSUE THREAD

**Issue by wanganping965** [lx865712528/JMEE#19]
`def train(model, train_set, dev_set, test_set, optimizer_constructor, epochs, tester, parser, other_testsets):
    # build batch on cpu
    train_iter = BucketIterator(train_set, batch_size=parser.batch, train=False, shuffle=True, device=-1,sort_key=lambda x: len(x.POSTAGS))`
   
but when i change the train to True,,, then i train it ,i found that most of train step the f1 and f, r are closed to 100%,,, so what's wrong with it?

**Comment by WAPING** [comment]
in the epoch1,the text rate will over 100% to ∞
