### ISSUE TITLE
Missing entity recognition component for prediction

### ISSUE THREAD

**Issue by mikelkl** [lx865712528/JMEE#7]
Hi there,

Thanks for your kindly code releasing.

when I was reading the code, I found that the [`golden-entity-mentions`](https://github.com/lx865712528/JMEE/blob/494451d5852ba724d273ee6f97602c60a5517446/ace-05-splits/sample.json#L35) data is provided in advance. Also, in `forward` function of `EDModel`, [`batch_golden_entities`](https://github.com/lx865712528/JMEE/blob/494451d5852ba724d273ee6f97602c60a5517446/enet/models/ee.py#L106) argument is required.

Does them mean when I wish to predict data without entity label, an extra NER system is needed to recognize entities before and then feed results into JMEE?

Thanks & Regards,
Mike

**Comment by airkid** [comment]
I believe so.  
In ACE2005 Dataset, the entity mention are pre given.  
If you want to apply this code to a plane text data set there should be a NER result before this project.

**Comment by mikelkl** [comment]
Hi @airkid, yeah, if our idea is correct, it's not a completed `joint model` I think.

**Comment by airkid** [comment]
Hi @mikelkl , `joint` means predict trigger and argument in one model in this task.  
The opposite model structure is called `pipe line` model, which extract event mention in `model 1` and send the result (text result) into `model 2` for argument extraction.  
In the source paper of this project, you can find `DMCNN` in the experiment part, which is a famous pipe line model as baseline method.

**Comment by mikelkl** [comment]
Hi @airkid , does DMCNN also need pre given entities? If so, maybe both the "joint" approach and the "pipeline" approach  assume entities is known, then maybe the argument extraction phase is actually the argument role classification for each entity-trigger pair.

**Comment by airkid** [comment]
Hi @mikelkl , you are right they both need per given entities.

**Comment by mikelkl** [comment]
@airkid well, it's not easy...
